version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - type: bind
        source: "server/world"
        target: "/home/minecraft/server/world"
    environment:
      RCON_PASSWORD: "creeper"
    restart: always
#   rcon:
#     image: itzg/rcon
#     ports:
#       - "4326:4326"
#       - "4327:4327"
#     volumes:
#       - "rcon:/opt/rcon-web-admin/db"

