version: "3.2"
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - /opt/minecraft/server/world:/home/minecraft/server/world
    environment:
      RCON_PASSWORD: "creeper"
    restart: always
