version: "3.2"
services:
  minecraft:
    build: .
    env_file: ./.env
    ports:
      - "25565:25565" # Minecraft
      - "25575:25575" # RCON
    volumes:
      - ./server/world:/home/minecraft/server/world
      - ./backups:/home/minecraft/backups
    restart: always
